name: Pull Request Details
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  print_details:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Pull Request Details:"
          echo "---------------------"
          echo "${{ github.event.pull_request }}"
          echo "Number: ${{ github.event.pull_request.number }}"
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Description: ${{ github.event.pull_request.body }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "URL: ${{ github.event.pull_request.html_url }}"
          echo "Branch Name : ${{ github.event.pull_request.head.ref }}"

  push_to_merge_queue:
    runs-on: ubuntu-latest
    needs: print_details

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push and Merge to Different Branch
      run: |
        TARGET_BRANCH="merge_queue"
        git checkout -B $TARGET_BRANCH
        git add .
        git commit -m "Merge code to $TARGET_BRANCH"
        git push origin $TARGET_BRANCH
